### ISSUE TITLE
Poseidon Hash support

### ISSUE THREAD

**Issue by eigmax** [novifinancial/winterfell#115]
Hi, @irakliyk, Is there any plan to support Poseidon Hash over GL or BN128？

**Comment by irakliyk** [comment]
After the work in #111 is completed, it will be possible to "bring your own hash function". So, it will be possible to implement Poseidon somewhere else and still use it with Winterfell.

**Comment by irakliyk** [comment]
Closed by #111.

**Comment by Nashtare** [comment]
@irakliyk does that mean we shouldn't provide additional hash functions over f64 on this repo?
I have something under the hood that I believe may be quite beneficial for projects relying on recursive composition with Winterfell, typically Miden. Is it worth suggesting it?

**Comment by irakliyk** [comment]
@Nashtare - I think it is fine to add more hash functions here. So, if there is something you'd like to add, definitely feel free to make a PR.

With the last set of updates we just made it more flexible for people who may not want to put their hash functions inside Winterfell.
