### ISSUE TITLE
[math] Remove rand crate dependency

### ISSUE THREAD

**Issue by irakliyk** [novifinancial/winterfell#37]
Ideally, this should be a dev dependency as we use methods which rely on `rand` crate almost exclusively for testing and benchmarking.

**Comment by Nashtare** [comment]
Out of curiosity (as the rand dependency is part of it by default), is some no-std support in the pipeline of this project?

**Comment by irakliyk** [comment]
Yes, we'd like to do this at least for the verifier. Though, hard to tell when it will actually happen.
