### ISSUE TITLE
Question about getting avoid of `panic` in the generated wasm binary

### ISSUE THREAD

**Issue by winderica** [novifinancial/winterfell#60]
Hi there. I'm working on a blockchain-related project which uses `winterfell` and I need to compile my code to WebAssembly, so that it can be executed on an EVM-compatible runtime.

I found that the generated wasm binary imports `core::panicking::panic` somehow, even if `panic = "abort"` is enabled:

```sh
> wasm-dis wasm32-unknown-unknown/release/contract.wasm | grep "import.*panic"
 (import "env" "_ZN4core9panicking5panic17h6619a393253f8e08E" (func $_ZN4core9panicking5panic17h6619a393253f8e08E (param i32 i32 i32)))
```

And this function is called by `$_ZN17compiler_builtins3int5shift4Ashl4ashl17h85b84ee9c80145b7E`, which is called by `$_ZN17compiler_builtins3int5shift9__ashlti317hbfcf8d3fd2119232E`, which is called by `$__ashlti3`, which is called by `$_ZN11winter_math5field6traits10StarkField17get_root_of_unity17hc9d7430c89370043E`.

And here is `$_ZN11winter_math5field6traits10StarkField17get_root_of_unity17hc9d7430c89370043E`:
https://github.com/novifinancial/winterfell/blob/f89e6c1011a9e3f42667905e94b81265d8999dae/math/src/field/traits.rs#L218-L227

So I guess rustc has some internal checks to ensure that the `shl` operation doesn't overflow, which always call `panic`.

I made the following change, and the compiled wasm no longer imports `panic`.
```diff
- let power = Self::PositiveInteger::from(1u32) << (Self::TWO_ADICITY - n);
- Self::TWO_ADIC_ROOT_OF_UNITY.exp(power)
+ let power = 1u64 << (Self::TWO_ADICITY - n); // `TWO_ADICITY` is 39 in f62, and 40 in f128, so u64 is sufficient (?)
+ Self::TWO_ADIC_ROOT_OF_UNITY.exp(Self::PositiveInteger::from(power))
```

Since I am a beginner both to rust and `winterfell`, I am wondering whether my modified code works in the same way.

If it makes sense, I am willing to submit a pull request.

**Comment by bobbinth** [comment]
Hi! Thank you for writing this up!

I'm not an expert on Rust to WASM compilation - so, not quite sure why left shift is causing issues (I'd think that `assert`'s would be using `panic` as well. Interesting that it's only the shift that's problematic). Quick question: do you get an error for both `debug` and `release` builds? Or just for `debug`? (usually, the compiler strips out overflow checking in `release` builds).

The code you've proposed will work fine with the field we have now, however, if we introduce fields with large two-addicity (greater than 64), it may produce incorrect results. So, I'd rather preserve a more general form. One way around this is to introduce a function which does this left shift explicitly, and then each field implementation can implement the function as is appropriate for it. But before we go this route, I'd like to make sure there are no other simpler solutions to this.

**Comment by irakliyk** [comment]
Hi! Thank you for writing this up!

I'm not an expert on Rust to WASM compilation - so, not quite sure why left shift is causing issues (I'd think that `assert`'s would be using `panic` as well. Interesting that it's only the shift that's problematic). Quick question: do you get an error for both `debug` and `release` builds? Or just for `debug`? (usually, the compiler strips out overflow checking in `release` builds).

The code you've proposed will work fine with the field we have now, however, if we introduce fields with large two-addicity (greater than 64), it may produce incorrect results. So, I'd rather preserve a more general form. One way around this is to introduce a function which does this left shift explicitly, and then each field implementation can implement the function as is appropriate for it. But before we go this route, I'd like to make sure there are no other simpler solutions to this.

**Comment by winderica** [comment]
It is weird that `panic` is only imported in `release` build, and here is what I found when digging into it.

---

First, my project uses a cargo subcommand [cargo-liquid](https://github.com/WeBankBlockchain/cargo-liquid). They don't provide a documentation in English, but this tool is in brief a wrapper of cargo.

When running `cargo liquid build`, it generates an executable binary (wasm) in release mode and its metadata (abi), and the actual command is equivalently `RUSTFLAGS="--sysroot $PWD/target/sysroot" cargo build --target=wasm32-unknown-unknown --no-default-features --release`. It seems that `cargo-liquid` generated a custom version of `rustlib` in `target/sysroot` before building.

---

I created a minimal reproducible project to show the differences between `cargo build` and `cargo liquid build`:

`Cargo.toml`:
```toml
[package]
edition = "2018"
name = "contract"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[profile.release] # this section is generated by the `new` command of `cargo-liquid`
lto = true
opt-level = "z"
panic = "abort"
overflow-checks = true
```

`src/lib.rs`:
```rs
#![no_std]
#![feature(core_intrinsics)]
use core::intrinsics;
use core::panic::PanicInfo;

#[no_mangle]
pub fn get_root_of_unity(n: u32) -> u128 {
    u128::from(1u32) << (40 - n)
}

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    intrinsics::abort()
}
```

---

* `cargo build`
    * debug: `cargo build --target=wasm32-unknown-unknown --no-default-features && wasm-dis ./target/wasm32-unknown-unknown/debug/contract.wasm | grep panic`, which outputs:
    ```
        (call $_ZN4core9panicking5panic17hc35917361a82c412E
      (call $_ZN4core9panicking5panic17hc35917361a82c412E
     (func $_ZN4core9panicking5panic17hc35917361a82c412E (param $0 i32) (param $1 i32) (param $2 i32)
      (call $_ZN4core9panicking9panic_fmt17h1ba034fb58bf295cE
     (func $_ZN4core9panicking9panic_fmt17h1ba034fb58bf295cE (param $0 i32) (param $1 i32)
    ```
    * release: `cargo build --target=wasm32-unknown-unknown --no-default-features --release && wasm-dis ./target/wasm32-unknown-unknown/release/contract.wasm | grep panic`, which outputs:
    ```
        (call $_ZN4core9panicking5panic17hc35917361a82c412E
       (call $_ZN4core9panicking5panic17hc35917361a82c412E
     (func $_ZN4core9panicking5panic17hc35917361a82c412E (param $0 i32) (param $1 i32)
      (call $_ZN4core9panicking9panic_fmt17h1ba034fb58bf295cE)
     (func $_ZN4core9panicking9panic_fmt17h1ba034fb58bf295cE
    ```
* `cargo liquid build`
    * debug: `RUSTFLAGS="--sysroot $PWD/target/sysroot" cargo build --target=wasm32-unknown-unknown --no-default-features && wasm-dis ./target/wasm32-unknown-unknown/debug/contract.wasm | grep panic`, which outputs:
    ```
        (call $_ZN4core9panicking5panic17h6619a393253f8e08E
      (call $_ZN4core9panicking5panic17h6619a393253f8e08E
      (call $_ZN4core9panicking5panic17h6619a393253f8e08E
     (func $_ZN4core9panicking5panic17h6619a393253f8e08E (param $0 i32) (param $1 i32) (param $2 i32)
    ```
    * release: `RUSTFLAGS="--sysroot $PWD/target/sysroot" cargo build --target=wasm32-unknown-unknown --no-default-features --release && wasm-dis ./target/wasm32-unknown-unknown/release/contract.wasm | grep panic`, which outputs:
    ```
     (import "env" "_ZN4core9panicking5panic17h6619a393253f8e08E" (func $_ZN4core9panicking5panic17h6619a393253f8e08E (param i32 i32 i32)))
      (call $_ZN4core9panicking5panic17h6619a393253f8e08E
    ```

So all of these commands produce `core::panicking::panic`, but the `import` statement is only introduced by `cargo-liquid` in the release mode and is not related to `winterfell`.

I'd like to write a little bit more before closing this issue. I turned each options in `[profile.release]` on and off, and found that it is `lto = true` that causes the error. (Although I cannot figure out why link time optimization imports this function rather than including it in the binary executable.)

Anyway, thank you for developing this awesome project. Cheers!

**Comment by irakliyk** [comment]
Thank you for the kind words and for such a detailed explanation!
